language: go
go:
    - 1.8
    - 1.7.3
    - 1.6
sudo: true

before_install:
    - touch /tmp/install.log
    - touch /tmp/logs
script:
    - which go
    - ls -l
    - make

matrix:
  fast_finish: true
  allow_failures:
      - go: 1.8
        env: TRAVIS_COVERAGE=1

notifications:
  email: false
