language: go
go:
    - 1.8
    - 1.7.3
    - 1.6
sudo: true 

before_install:  
    - touch /tmp/install.log
script:
    - which go
    - cd ./src/ 
    - ls -l
    - make 

notifications:
  email: false
